# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
#orbs:
#  node: circleci/node@4.7

defaults: &defaults
  working_directory: ~
  docker:
    - image: circleci/node:14.15.0

jobs:
  test:
    <<: *defaults
    steps:
      # Must checkout first to obtain git_deploy_key.enc
      - checkout
      - run:
          # Decrypt the git_deploy_key.enc key into /tmp/git_deploy_key
          name: Decrypt Deploy Key
          command: openssl aes-256-cbc -d -K $REPO_ENC_KEY -iv $REPO_ENC_IV -in git_deploy_key.enc -out /tmp/git_deploy_key
      - run:
          # Make sure only the current user can read the private key
          name: chmod the key
          command: chmod 600 /tmp/git_deploy_key
      - run:
          # Create a script to return the passphrase environment variable to ssh-add
          name: Create Script to get PP env
          command: echo 'echo ${SSL_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
      - run:
          # Start the authentication agent
          name: Start authentication agent
          command: eval "$(ssh-agent -s)"
      - run:
          # Add the key to the authentication agent
          name: Add key to authentication agent
          command: DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/git_deploy_key </dev/null
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Change NPM path
          command: mkdir ~/.npm-global && npm config set prefix '~/.npm-global' 
      - run:
          name: Export NPM path
          command: export PATH=~/.npm-global/bin:$PATH && source ~/.profile
      - run:
          name: Install Gatsby CLI
          command: npm install -g gatsby-cli
      - run:
          name: Install GitHub Pages
          command: npm install gh-pages
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~
      - run:
          name: Build and Deploy
          command: npm run deploy

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
        #  filters:
        #    tags:
        #      only: /^v.*/
      - deploy:
          requires:
            - test
       #   filters:
       #     tags:
       #       only: /^v.*/
       #     branches:
       #       ignore: /.*/
