version: 2.1

defaults: &defaults
  working_directory: ~/will-coquillette
  docker:
    - image: circleci/node:14.15.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Change NPM path
          command: mkdir ~/.npm-global && npm config set prefix '~/.npm-global' 
      - run:
          name: Export NPM path
          command: export PATH=~/.npm-global/bin:$PATH && source ~/.profile
      - run:
          name: Install Gatsby CLI
          command: |
            npm install -g gatsby-cli
            npm -g ls --depth=0
      - run:
          name: Build With Gatsby
          command: |
            gatsby build --prefix-paths
            cp CNAME public/
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/will-coquillette
          paths: .
           
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/will-coquillette
      - add_ssh_keys:
          fingerprints:
            - "9f:c8:35:7c:6c:1f:a6:fe:cb:50:07:bc:82:e4:27:12"           
      - run:
          name: Git Config
          command: |
            git config --global user.email "4646219+willquill@users.noreply.github.com"
            git config --global user.name "Circle CI"
      - run:
          name: Install GitHub Pages
          command: npm install gh-pages
      - run:
          name: Deploy
          command: gh-pages -d public

workflows:
  version: 2
  test-deploy:
    jobs:
      - build
        #  filters:
        #    tags:
        #      only: /^v.*/
      - deploy:
          requires:
            - build
       #   filters:
       #     tags:
       #       only: /^v.*/
       #     branches:
       #       ignore: /.*/
