# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
#orbs:
#  node: circleci/node@4.7

defaults: &defaults
  working_directory: ~/will-coquillette
  docker:
    - image: circleci/node:14.15.0

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      #- run:
      #    name: NPM Install
      #    command: npm install
      - run:
          name: Change NPM path
          command: mkdir ~/.npm-global && npm config set prefix '~/.npm-global' 
      - run:
          name: Export NPM path
          command: export PATH=~/.npm-global/bin:$PATH && source ~/.profile
      - run:
          name: Install Gatsby CLI
          command: npm install -g gatsby-cli
      - run:
          name: Install GitHub Pages
          command: npm install gh-pages
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/will-coquillette
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/will-coquillette
      - add_ssh_keys:
          fingerprints:
            - "IZ1Bj67n9zslwRrx2cqgiLXNoJSNJEDFVYqWs8YisW0"
      - run:
          name: Build and Deploy
          command: npm run deploy

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
        #  filters:
        #    tags:
        #      only: /^v.*/
      - deploy:
          requires:
            - test
       #   filters:
       #     tags:
       #       only: /^v.*/
       #     branches:
       #       ignore: /.*/
